# Generated by Django 5.2.5 on 2025-09-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('explorers', '0003_sectiontophotomodel_sectionmodel_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='photomodel',
            name='sections',
            field=models.ManyToManyField(related_name='photo_routes', through='explorers.SectionToPhotoModel', to='explorers.sectionmodel', verbose_name='Associated Routes.'),
        ),
    ]
