# Generated by Django 5.2.5 on 2025-09-13 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filemodel',
            old_name='file',
            new_name='path',
        ),
    ]
