# Generated by Django 5.2.5 on 2025-09-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(help_text='Path where the file is stored.', upload_to='', verbose_name='File Path'),
        ),
        migrations.AlterField(
            model_name='photomodel',
            name='path',
            field=models.ImageField(help_text='Path where the photo is stored.', upload_to='', verbose_name='Photo Path'),
        ),
    ]
