# Generated by Django 5.2.5 on 2025-09-04 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_alter_filemodel_file_alter_photomodel_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(help_text='Path where the file is stored.', upload_to='files/', verbose_name='File Path'),
        ),
    ]
