# Generated by Django 5.2.5 on 2025-11-22 10:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeLogModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the object, automatically generated as a UUIDv4 value.', primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(blank=True, help_text='The name of the application that this object belongs to. This helps in identifying the application context of the object.', max_length=64, null=True, verbose_name='Object application name')),
                ('model_name', models.CharField(blank=True, help_text='The name of the model that this object is an instance of. This helps in identifying the type of the object.', max_length=64, null=True, verbose_name='Object model name')),
                ('object_id', models.CharField(blank=True, help_text='The primary key (PK) number of the correlated object. This is a unique identifier for the object within its model.', max_length=64, null=True, verbose_name='Object PK number')),
                ('object_repr', models.CharField(blank=True, help_text='A string representation of the object. This provides a human-readable description or identifier of the object.', max_length=128, null=True, verbose_name='Object representation')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The date and time when the change was created. This field automatically records the exact moment when the change entry is added to the log.', verbose_name='Timestamp')),
                ('is_public', models.BooleanField(default=True, help_text='Indicates whether the object is publicly accessible (True) or private (False). If set to True, the object will be visible to all users and guests.', verbose_name='Is Public')),
                ('action_type', models.IntegerField(choices=[(0, 'Empty'), (1, 'Create'), (2, 'Update'), (3, 'Delete')], default=0, help_text='The type of action that was performed on the object. This could include actions such as creation, modification, or deletion of records. The choices are defined in the ActionTypeChoices constant.', verbose_name='Type of action')),
                ('after', models.JSONField(blank=True, help_text='The JSON representation of the object after the changes were made and saved to the database. This provides a snapshot of the object state post-change for auditing and rollback purposes.', null=True, verbose_name='JSON object representation after change')),
            ],
            options={
                'verbose_name': 'Change',
                'verbose_name_plural': 'Changes',
                'permissions': [('change_own_changelogmodel', 'Can change own changes'), ('change_all_changelogmodel', 'Can change all changes'), ('delete_own_changelogmodel', 'Can delete own changes'), ('delete_all_changelogmodel', 'Can delete all changes'), ('view_own_changelogmodel', 'Can view own changes'), ('view_all_changelogmodel', 'Can view all changes'), ('add_own_changelogmodel', 'Can add own changes')],
            },
        ),
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the object, automatically generated as a UUIDv4 value.', primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='The date and time when the notification was created. This field is automatically populated when the notification is created.', verbose_name='Timestamp')),
                ('severity', models.IntegerField(choices=[(1, 'Critical'), (2, 'Error'), (3, 'Warning'), (4, 'Info'), (5, 'Debug')], default=0, help_text='The severity level of the notification. Indicates the importance or urgency of the notification.', verbose_name='Severity level')),
                ('task_id', models.CharField(blank=True, help_text='The unique identifier of the task associated with this notification. Helps in tracking and correlating notifications to specific tasks.', max_length=64, null=True, verbose_name='Task ID')),
                ('message', models.CharField(error_messages={'invalid': 'Enter a valid notification message. It must contain between 1 and 1024 characters.'}, help_text='The notification message detailing the event or action. This message provides information about the notification. The message must be between 1 and 1024 characters long.', max_length=1024, verbose_name='Message')),
                ('object_url', models.CharField(blank=True, help_text='The URL to the object related to this notification. This can be used to provide a direct link to the relevant object or page within the application.', max_length=256, null=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'permissions': [('change_own_notificationmodel', 'Can change own notifications'), ('change_all_notificationmodel', 'Can change all notifications'), ('delete_own_notificationmodel', 'Can delete own notifications'), ('delete_all_notificationmodel', 'Can delete all notifications'), ('view_own_notificationmodel', 'Can view own notifications'), ('view_all_notificationmodel', 'Can view all notifications'), ('add_own_notificationmodel', 'Can add own notifications')],
            },
        ),
    ]
