# Generated by Django 5.2.5 on 2025-12-16 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='changelogmodel',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='The user responsible for the change. This field links to the user who performed the action, providing accountability and traceability.', null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
    ]
