# Generated by Django 5.2.5 on 2025-09-01 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changelogmodel',
            name='created',
        ),
        migrations.RemoveField(
            model_name='changelogmodel',
            name='updated',
        ),
    ]
