# Generated by Django 5.2.5 on 2025-08-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changelogmodel',
            options={'default_permissions': (), 'permissions': (('read_write_changelogmodel', 'Read and write access.'), ('read_only_changelogmodel', 'Read only access')), 'verbose_name': 'Change', 'verbose_name_plural': 'Changes'},
        ),
        migrations.AlterModelOptions(
            name='notificationmodel',
            options={'default_permissions': (), 'permissions': (('read_write_notificationmodel', 'Read and write access.'), ('read_only_notificationmodel', 'Read only access')), 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
    ]
