# Generated by Django 5.2.5 on 2025-08-28 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_changelogmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changelogmodel',
            options={'default_permissions': (), 'permissions': (('read_write', 'Read and write access.'), ('read_only', 'Read only access')), 'verbose_name': 'Change', 'verbose_name_plural': 'Changes'},
        ),
        migrations.AlterModelOptions(
            name='notificationmodel',
            options={'default_permissions': (), 'permissions': (('read_write', 'Read and write access.'), ('read_only', 'Read only access')), 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
    ]
