# Generated by Django 5.2.5 on 2025-08-28 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_changelogmodel_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changelogmodel',
            options={'verbose_name': 'Change', 'verbose_name_plural': 'Changes'},
        ),
        migrations.AlterModelOptions(
            name='notificationmodel',
            options={'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
    ]
