# Generated by Django 5.2.5 on 2025-08-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_changelogmodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='changelogmodel',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Indicates whether the object is publicly accessible (True) or private (False). If set to True, the object will be visible to all users and guests.', verbose_name='Is Public'),
        ),
        migrations.AddField(
            model_name='notificationmodel',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Indicates whether the object is publicly accessible (True) or private (False). If set to True, the object will be visible to all users and guests.', verbose_name='Is Public'),
        ),
    ]
