# Generated by Django 5.2.5 on 2025-08-28 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_changelogmodel_is_public_notificationmodel_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changelogmodel',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='notificationmodel',
            name='is_public',
        ),
    ]
