# Generated by Django 5.2.5 on 2025-08-28 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0007_remove_changelogmodel_is_public_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationmodel',
            old_name='url',
            new_name='object_url',
        ),
    ]
