# Generated by Django 5.2.5 on 2025-11-18 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_initial'),
        ('compendiums', '0002_initial'),
        ('explorers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='routemodel',
            name='creator',
            field=models.ForeignKey(help_text='Stores the unique identifier (UUID) of the user who created the object. This field is used to track ownership of the object.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='routemodel',
            name='users_accomplished',
            field=models.ManyToManyField(help_text='Users who have accomplished or completed this %(class)s. Allows queries of which members completed a %(class)s.', related_name='%(class)s_users_accomplished', to=settings.AUTH_USER_MODEL, verbose_name='Users Accomplished'),
        ),
        migrations.AddField(
            model_name='routemodel',
            name='users_liked',
            field=models.ManyToManyField(help_text='Users who liked this %(class)s. Used to record engagement and allow retrieval of which members expressed a positive reaction.', related_name='%(class)s_users_liked', to=settings.AUTH_USER_MODEL, verbose_name='Users Liked'),
        ),
        migrations.AddField(
            model_name='sectionmodel',
            name='creator',
            field=models.ForeignKey(help_text='Stores the unique identifier (UUID) of the user who created the object. This field is used to track ownership of the object.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='sectionmodel',
            name='end_poi',
            field=models.ForeignKey(help_text='The logical ending Point of Interest for this Section. This PoI marks where the Section concludes. It is often a hut, pass, road, summit, or transition point where the next Section begins.', on_delete=django.db.models.deletion.PROTECT, related_name='poi_sections_end', to='compendiums.poimodel', verbose_name='End PoI'),
        ),
        migrations.AddField(
            model_name='sectionmodel',
            name='gpx_data',
            field=models.ForeignKey(blank=True, help_text='GPX data file.', null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.filemodel', verbose_name='GPX Data'),
        ),
        migrations.AddField(
            model_name='sectionmodel',
            name='start_poi',
            field=models.ForeignKey(help_text='The logical starting Point of Interest for this Section. This PoI acts as the anchor at the beginning of the GPX geometry. It often represents a village, pass entrance, hut, or junction where the Section officially begins.', on_delete=django.db.models.deletion.PROTECT, related_name='poi_sections_start', to='compendiums.poimodel', verbose_name='Start PoI'),
        ),
        migrations.AddField(
            model_name='sectionmodel',
            name='users_liked',
            field=models.ManyToManyField(help_text='Users who liked this %(class)s. Used to record engagement and allow retrieval of which members expressed a positive reaction.', related_name='%(class)s_users_liked', to=settings.AUTH_USER_MODEL, verbose_name='Users Liked'),
        ),
        migrations.AddField(
            model_name='sectiontophotomodel',
            name='photo',
            field=models.ForeignKey(help_text='The Photo that is associated with the Section to Photo M2M relationship.', on_delete=django.db.models.deletion.PROTECT, related_name='section_photo_associations', to='assets.photomodel', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='sectiontophotomodel',
            name='section',
            field=models.ForeignKey(help_text='The Section that is associated with the Photo to Section M2M relationship.', on_delete=django.db.models.deletion.PROTECT, related_name='photo_section_associations', to='explorers.sectionmodel', verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='sectionmodel',
            name='photos',
            field=models.ManyToManyField(help_text='Photos that visually document this Section. These images may include landscape views, trail markers, huts, technical areas, bridges, seasonal conditions, or user-submitted impressions. This media enriches the map and helps users understand terrain difficulty, exposure, or scenic value.', related_name='section_photos', through='explorers.SectionToPhotoModel', to='assets.photomodel', verbose_name='Section Photos'),
        ),
        migrations.AddField(
            model_name='sectiontopoimodel',
            name='poi',
            field=models.ForeignKey(help_text='The Point of Interest that is associated with the Section to Point of Interest M2M relationship.', on_delete=django.db.models.deletion.PROTECT, related_name='section_poi_associations', to='compendiums.poimodel', verbose_name='Point of Interest'),
        ),
        migrations.AddField(
            model_name='sectiontopoimodel',
            name='section',
            field=models.ForeignKey(help_text='The Section that is associated with the Point of Interest to Section M2M relationship.', on_delete=django.db.models.deletion.PROTECT, related_name='poi_section_associations', to='explorers.sectionmodel', verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='sectionmodel',
            name='pois',
            field=models.ManyToManyField(help_text='Points of Interest that structure and annotate this Section. PoIs mark meaningful locations like summits, huts, passes, lakes, cultural sites, trail junctions, or wayfinding references. PoIs provide semantic meaning to the raw GPX path and help users navigate and understand the Section.', related_name='section_pois', through='explorers.SectionToPoiModel', to='compendiums.poimodel', verbose_name='Section Points of Interest (PoIs)'),
        ),
        migrations.AddField(
            model_name='sectiontoregionmodel',
            name='region',
            field=models.ForeignKey(help_text='The Region that is associated with the Section to Region M2M relationship.', on_delete=django.db.models.deletion.PROTECT, related_name='section_region_associations', to='compendiums.regionmodel', verbose_name='Region'),
        ),
        migrations.AddField(
            model_name='sectiontoregionmodel',
            name='section',
            field=models.ForeignKey(help_text='The Section that is associated with the Region to Section M2M relationship.', on_delete=django.db.models.deletion.PROTECT, related_name='region_section_associations', to='explorers.sectionmodel', verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='sectionmodel',
            name='regions',
            field=models.ManyToManyField(help_text='Geographical regions that this Section traverses or belongs to. Regions support filtering, browsing, and map-based exploration. A Section may span multiple regions if it crosses borders or large geographic areas.', related_name='section_regions', through='explorers.SectionToRegionModel', to='compendiums.regionmodel', verbose_name='Section Regions'),
        ),
        migrations.AddField(
            model_name='sectiontoroutemodel',
            name='route',
            field=models.ForeignKey(help_text='The Route that is associated with the Section to Route M2M relationship.', on_delete=django.db.models.deletion.CASCADE, related_name='section_route_associations', to='explorers.routemodel', verbose_name='Route'),
        ),
        migrations.AddField(
            model_name='sectiontoroutemodel',
            name='section',
            field=models.ForeignKey(help_text='The Section that is associated with the Section to Trip M2M relationship.', on_delete=django.db.models.deletion.CASCADE, related_name='section_trip_associations', to='explorers.sectionmodel', verbose_name='Section'),
        ),
        migrations.AddField(
            model_name='sectionmodel',
            name='routes',
            field=models.ManyToManyField(help_text='Routes that contain this Section. Routes are composed of multiple Sections arranged in a defined order. The same Section may appear in multiple Routes (e.g., shared valley trails or ridge lines).', related_name='route_sections', through='explorers.SectionToRouteModel', to='explorers.routemodel', verbose_name='Route Sections'),
        ),
        migrations.AddField(
            model_name='routemodel',
            name='sections',
            field=models.ManyToManyField(help_text='The ordered list of Sections that form this Route. Sections are the atomic segments of a Route, each defining its own geometry, start/end PoIs, intermediate PoIs, regions, and characteristics. The order of Sections is controlled by the through-model "SectionToRouteModel", which includes a sequence index for precise arrangement of stage progression.', related_name='route_sections', through='explorers.SectionToRouteModel', to='explorers.sectionmodel', verbose_name='Sections'),
        ),
        migrations.AddField(
            model_name='tripmodel',
            name='creator',
            field=models.ForeignKey(help_text='Stores the unique identifier (UUID) of the user who created the object. This field is used to track ownership of the object.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='tripmodel',
            name='users_accomplished',
            field=models.ManyToManyField(help_text='Users who have accomplished or completed this %(class)s. Allows queries of which members completed a %(class)s.', related_name='%(class)s_users_accomplished', to=settings.AUTH_USER_MODEL, verbose_name='Users Accomplished'),
        ),
        migrations.AddField(
            model_name='tripmodel',
            name='users_liked',
            field=models.ManyToManyField(help_text='Users who liked this %(class)s. Used to record engagement and allow retrieval of which members expressed a positive reaction.', related_name='%(class)s_users_liked', to=settings.AUTH_USER_MODEL, verbose_name='Users Liked'),
        ),
        migrations.AddField(
            model_name='triptoroutemodel',
            name='poi',
            field=models.ForeignKey(blank=True, help_text='The point of interest associated with Route to Trip M2M relationship.', null=True, on_delete=django.db.models.deletion.PROTECT, to='compendiums.poimodel', verbose_name='Point of Interest'),
        ),
        migrations.AddField(
            model_name='triptoroutemodel',
            name='route',
            field=models.ForeignKey(help_text='The Route that is associated with the Trip to Route M2M relationship.', on_delete=django.db.models.deletion.PROTECT, related_name='trip_route_associations', to='explorers.routemodel', verbose_name='Route'),
        ),
        migrations.AddField(
            model_name='triptoroutemodel',
            name='trip',
            field=models.ForeignKey(help_text='The Trip that is associated with the Route to Trip M2M relationship.', on_delete=django.db.models.deletion.PROTECT, related_name='route_trip_associations', to='explorers.tripmodel', verbose_name='Trip'),
        ),
        migrations.AddField(
            model_name='tripmodel',
            name='routes',
            field=models.ManyToManyField(help_text='Routes that form the planned structure of this Trip. Each Route represents an official segment or stage of the intended multi-day itinerary, defining planned geometry, pacing, and difficulty. This selection represents the ideal blueprint that a user may later choose to follow during an executed Journey.', related_name='trip_routes', through='explorers.TripToRouteModel', to='explorers.routemodel', verbose_name='Planned Routes'),
        ),
        migrations.AddField(
            model_name='routemodel',
            name='trips',
            field=models.ManyToManyField(help_text='A list of Trips that incorporate this Route as part of a planned multi-day itinerary. This allows official Routes to be used as building blocks inside larger trip structures.', related_name='route_trips', through='explorers.TripToRouteModel', to='explorers.tripmodel', verbose_name='Route Trips'),
        ),
    ]
