# Generated by Django 5.2.5 on 2025-09-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compendiums', '0003_poimodel_sections_regionmodel_sections'),
        ('explorers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectionmodel',
            name='sections',
        ),
        migrations.AddField(
            model_name='sectionmodel',
            name='cards',
            field=models.ManyToManyField(help_text='Cards associated with the section that can be obtained by the user by completing this section.', related_name='section_cards', through='explorers.SectionToCardModel', to='compendiums.cardmodel', verbose_name='Section Cards'),
        ),
        migrations.AlterField(
            model_name='sectionmodel',
            name='average_grade',
            field=models.FloatField(blank=True, help_text='The average percentage of incline over the entire route, calculated as (total elevation gain / total distance) x 100. A higher value indicates a steeper route.', null=True, verbose_name='Average Grade'),
        ),
        migrations.AlterField(
            model_name='sectionmodel',
            name='distance',
            field=models.FloatField(blank=True, help_text='The total length of the route, measured in kilometres. This includes the full distance from start to finish, including both flat and uphill sections.', null=True, verbose_name='Route Distance'),
        ),
        migrations.AlterField(
            model_name='sectionmodel',
            name='duration',
            field=models.FloatField(blank=True, help_text="User estimated total time required to complete the route, measured in hours. This estimate considers the user's predicted hiking pace along with elevation changes but may still be influenced by factors such as weather conditions and trail difficulty.", null=True, verbose_name='Estimated Duration'),
        ),
        migrations.AlterField(
            model_name='sectionmodel',
            name='elevation_gain',
            field=models.FloatField(blank=True, help_text='Total amount of ascent measured in meters. This is the cumulative elevation gain over the entire route, adding up all the uphill sections.', null=True, verbose_name='Elevation Gain'),
        ),
        migrations.AlterField(
            model_name='sectionmodel',
            name='elevation_loss',
            field=models.FloatField(blank=True, help_text='Total amount of descent measured in meters. This is the cumulative descent over the entire route, adding up all downhill sections.', null=True, verbose_name='Elevation Loss'),
        ),
        migrations.AlterField(
            model_name='sectionmodel',
            name='geojson',
            field=models.JSONField(blank=True, help_text='GeoJSON representation of the route path. Created based on provided GPX file.', null=True, verbose_name='Route GeoJSON Data'),
        ),
        migrations.AlterField(
            model_name='sectionmodel',
            name='highest_elevation',
            field=models.FloatField(blank=True, help_text='Maximum altitude reached along the route, measured in meters above sea level.', null=True, verbose_name='Highest Elevation'),
        ),
        migrations.AlterField(
            model_name='sectionmodel',
            name='highest_grade',
            field=models.FloatField(blank=True, help_text='The steepest percentage climb at any point on the route. This is the most challenging section in terms of gradient.', null=True, verbose_name='Maximum Grade'),
        ),
        migrations.AlterField(
            model_name='sectionmodel',
            name='lowest_elevation',
            field=models.FloatField(blank=True, help_text='Minimum altitude encountered along the route, measured in meters above sea level.', null=True, verbose_name='Lowest Elevation'),
        ),
    ]
