# Generated by Django 5.2.5 on 2025-12-30 10:37

import alpenwegs.ashared.validators.base_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journeymodel',
            name='snippet',
            field=models.CharField(blank=True, help_text='A short description of the object, between 8 and 512 characters. It may include letters, numbers, spaces, and the special characters -, _, and .', max_length=512, null=True, validators=[alpenwegs.ashared.validators.base_validators.SnippetValueValidator()], verbose_name='Snippet'),
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='snippet',
            field=models.CharField(blank=True, help_text='A short description of the object, between 8 and 512 characters. It may include letters, numbers, spaces, and the special characters -, _, and .', max_length=512, null=True, validators=[alpenwegs.ashared.validators.base_validators.SnippetValueValidator()], verbose_name='Snippet'),
        ),
        migrations.AlterField(
            model_name='sectionmodel',
            name='snippet',
            field=models.CharField(blank=True, help_text='A short description of the object, between 8 and 512 characters. It may include letters, numbers, spaces, and the special characters -, _, and .', max_length=512, null=True, validators=[alpenwegs.ashared.validators.base_validators.SnippetValueValidator()], verbose_name='Snippet'),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='snippet',
            field=models.CharField(blank=True, help_text='A short description of the object, between 8 and 512 characters. It may include letters, numbers, spaces, and the special characters -, _, and .', max_length=512, null=True, validators=[alpenwegs.ashared.validators.base_validators.SnippetValueValidator()], verbose_name='Snippet'),
        ),
        migrations.AlterField(
            model_name='tripmodel',
            name='snippet',
            field=models.CharField(blank=True, help_text='A short description of the object, between 8 and 512 characters. It may include letters, numbers, spaces, and the special characters -, _, and .', max_length=512, null=True, validators=[alpenwegs.ashared.validators.base_validators.SnippetValueValidator()], verbose_name='Snippet'),
        ),
    ]
