# Generated by Django 5.2.5 on 2025-09-04 15:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        ('explorers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionToPhotoModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the object, automatically generated as a UUIDv4 value.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Stores the date and time when the object was firstly created. This timestamp field is automatically set when the object is created and cannot be modified after creation.', verbose_name='Created Timestamp')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Records the date and time when the object was last updated. This timestamp field is automatically updated whenever the object is modified.', verbose_name='Updated Timestamp')),
                ('photo', models.ForeignKey(help_text='The Photo that is associated with the Section to Photo M2M relationship.', on_delete=django.db.models.deletion.PROTECT, related_name='section_photo_associations', to='assets.photomodel', verbose_name='Photo')),
                ('section', models.ForeignKey(help_text='The Section that is associated with the Photo to Section M2M relationship.', on_delete=django.db.models.deletion.PROTECT, related_name='photo_section_associations', to='explorers.sectionmodel', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Base Relationship Model',
                'verbose_name_plural': 'Base Relationship Models',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sectionmodel',
            name='photos',
            field=models.ManyToManyField(help_text='A collection of photos that are linked to the section and that provide a visual documentation of the section created by the section creator.', related_name='section_photos', through='explorers.SectionToPhotoModel', to='assets.photomodel', verbose_name='Section Photos'),
        ),
    ]
