# Generated by Django 5.2.5 on 2025-09-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorers', '0003_routemodel_tripmodel_triptoroutemodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routemodel',
            name='description',
            field=models.TextField(blank=True, help_text='A detailed description of the object. Supports plain text, rich text, or Markdown. Intended for contextual details such as terrain, difficulty level, notable landmarks, scenic highlights, and any other creator-provided insights.', null=True, verbose_name='Detail Description'),
        ),
        migrations.AlterField(
            model_name='sectionmodel',
            name='description',
            field=models.TextField(blank=True, help_text='A detailed description of the object. Supports plain text, rich text, or Markdown. Intended for contextual details such as terrain, difficulty level, notable landmarks, scenic highlights, and any other creator-provided insights.', null=True, verbose_name='Detail Description'),
        ),
        migrations.AlterField(
            model_name='tripmodel',
            name='description',
            field=models.TextField(blank=True, help_text='A detailed description of the object. Supports plain text, rich text, or Markdown. Intended for contextual details such as terrain, difficulty level, notable landmarks, scenic highlights, and any other creator-provided insights.', null=True, verbose_name='Detail Description'),
        ),
        migrations.AlterField(
            model_name='triptoroutemodel',
            name='description',
            field=models.TextField(blank=True, help_text='A detailed description of the object. Supports plain text, rich text, or Markdown. Intended for contextual details such as terrain, difficulty level, notable landmarks, scenic highlights, and any other creator-provided insights.', null=True, verbose_name='Detail Description'),
        ),
    ]
