# Generated by Django 5.2.5 on 2025-11-25 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
        ('explorers', '0003_journeymodel_trackmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sectionmodel',
            old_name='duration',
            new_name='estimated_duration',
        ),
        migrations.RemoveField(
            model_name='sectionmodel',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='trackmodel',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='trackmodel',
            name='minimum_speed',
        ),
        migrations.AddField(
            model_name='routemodel',
            name='estimated_duration',
            field=models.FloatField(blank=True, help_text="User estimated total time required to complete the route, measured in hours. This estimate considers the user's predicted hiking pace along with elevation changes but may still be influenced by factors such as weather conditions and trail difficulty.", null=True, verbose_name='Estimated Duration'),
        ),
        migrations.AddField(
            model_name='sectionmodel',
            name='total_distance',
            field=models.FloatField(blank=True, help_text='Total traversable route length computed from the GPX coordinates, including 3D distance calculation when elevation differences are present.', null=True, verbose_name='Total Distance (meters)'),
        ),
        migrations.AddField(
            model_name='sectionmodel',
            name='total_points',
            field=models.IntegerField(blank=True, help_text='Total number of individual track coordinate points recorded across every track segment in the GPX dataset. Higher values indicate greater GPS sampling density.', null=True, verbose_name='Total GPX Points'),
        ),
        migrations.AddField(
            model_name='trackmodel',
            name='ascent_average_speed',
            field=models.FloatField(blank=True, help_text='Represents the average speed achieved during climbing sections. Useful for analyzing uphill performance and physical effort in elevation gain.', null=True, verbose_name='Ascent Average Speed km/h'),
        ),
        migrations.AddField(
            model_name='trackmodel',
            name='descent_average_speed',
            field=models.FloatField(blank=True, help_text='Represents the average speed achieved during descending sections. Useful for determining control technique and confidence on steep segments.', null=True, verbose_name='Descent Average Speed km/h'),
        ),
        migrations.AddField(
            model_name='trackmodel',
            name='maximum_ascent_speed',
            field=models.FloatField(blank=True, help_text='Represents the highest recorded climbing speed along the full activity track. Indicates peak uphill efficiency and maximum physical performance.', null=True, verbose_name='Maximum Ascent Speed km/h'),
        ),
        migrations.AddField(
            model_name='trackmodel',
            name='maximum_descent_speed',
            field=models.FloatField(blank=True, help_text='Represents the highest recorded descending speed during the activity. Highlights the fastest downhill section in the full tracked route.', null=True, verbose_name='Maximum Descent Speed km/h'),
        ),
        migrations.AddField(
            model_name='trackmodel',
            name='moving_average_speed',
            field=models.FloatField(blank=True, help_text='Represents the average speed measured only during periods of recorded movement. Excludes all stop intervals from the calculation to reflect pure travel speed.', null=True, verbose_name='Moving Average Speed km/h'),
        ),
        migrations.AddField(
            model_name='trackmodel',
            name='overall_average_speed',
            field=models.FloatField(blank=True, help_text='Represents the average speed measured across the entire activity period including both movement and pauses. This value reflects the complete performance progression.', null=True, verbose_name='Overall Average Speed km/h'),
        ),
        migrations.AddField(
            model_name='trackmodel',
            name='stop_time',
            field=models.FloatField(blank=True, help_text='Total duration of all pauses recorded throughout the activity. Represents the accumulated period when the user was stationary.', null=True, verbose_name='Stop Time hours'),
        ),
        migrations.AddField(
            model_name='trackmodel',
            name='total_distance',
            field=models.FloatField(blank=True, help_text='Total traversable route length computed from the GPX coordinates, including 3D distance calculation when elevation differences are present.', null=True, verbose_name='Total Distance (meters)'),
        ),
        migrations.AddField(
            model_name='trackmodel',
            name='total_points',
            field=models.IntegerField(blank=True, help_text='Total number of individual track coordinate points recorded across every track segment in the GPX dataset. Higher values indicate greater GPS sampling density.', null=True, verbose_name='Total GPX Points'),
        ),
        migrations.AlterField(
            model_name='sectionmodel',
            name='elevation_graph',
            field=models.JSONField(blank=True, help_text='Structured dataset used to construct an elevation profile chart. Provides the height progression along the full track distance.', null=True, verbose_name='Elevation Graph'),
        ),
        migrations.AlterField(
            model_name='sectionmodel',
            name='geojson',
            field=models.JSONField(blank=True, help_text='Stores the GeoJSON representation of the route. This data is generated from the GPX file to allow visual mapping and geographical inspection in a standard format.', null=True, verbose_name='Route GeoJSON Data'),
        ),
        migrations.AlterField(
            model_name='sectionmodel',
            name='gpx_data',
            field=models.ForeignKey(blank=True, help_text='Stores the uploaded GPX file used to create and extract route information. It contains the raw measurement data required for distance elevation and grade analysis.', null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.filemodel', verbose_name='GPX Data'),
        ),
        migrations.AlterField(
            model_name='sectionmodel',
            name='highest_elevation',
            field=models.FloatField(blank=True, help_text='The highest altitude point measured along the recorded route. This metric helps determine alpine difficulty levels.', null=True, verbose_name='Highest Elevation'),
        ),
        migrations.AlterField(
            model_name='sectionmodel',
            name='lowest_elevation',
            field=models.FloatField(blank=True, help_text='The lowest altitude point measured along the route. This value defines the minimum elevation reached during the activity.', null=True, verbose_name='Lowest Elevation'),
        ),
        migrations.AlterField(
            model_name='sectionmodel',
            name='track_types',
            field=models.JSONField(blank=True, help_text='Stores descriptive information about the route terrain. This may include surface type difficulty and structure segments.', null=True, verbose_name='Track Types'),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='average_heart_rate',
            field=models.FloatField(blank=True, help_text='Average heart rate sustained over the full duration of the activity. Indicates exertion levels and fitness capacity.', null=True, verbose_name='Average Heart Rate (bpm)'),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='average_speed',
            field=models.FloatField(blank=True, help_text='Average traveling speed measured across the full activity. This value reflects the general pace over the entire route.', null=True, verbose_name='Average Speed (km/h)'),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='calories_burned',
            field=models.FloatField(blank=True, help_text='Estimated total energy expenditure registered during the activity. Helps evaluate effort and metabolic load.', null=True, verbose_name='Calories Burned (kcal)'),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='duration',
            field=models.FloatField(blank=True, help_text='Total recorded time of the activity, measured in hours. This value is derived from the tracked GPX data and reflects the actual movement and pauses during the route.', null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='elevation_graph',
            field=models.JSONField(blank=True, help_text='Structured dataset used to construct an elevation profile chart. Provides the height progression along the full track distance.', null=True, verbose_name='Elevation Graph'),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='end_time',
            field=models.DateTimeField(blank=True, help_text='Marks the exact time when the activity recording finished. Used to determine total duration and to close the activity timeline.', null=True, verbose_name='Track End Time'),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='equipment_used',
            field=models.CharField(blank=True, help_text='Optional description of used equipment such as boots or hiking poles. Useful for determining conditions and load.', max_length=512, null=True, verbose_name='Equipment Used'),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='geojson',
            field=models.JSONField(blank=True, help_text='Stores the GeoJSON representation of the route. This data is generated from the GPX file to allow visual mapping and geographical inspection in a standard format.', null=True, verbose_name='Route GeoJSON Data'),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='gpx_data',
            field=models.ForeignKey(blank=True, help_text='Stores the uploaded GPX file used to create and extract route information. It contains the raw measurement data required for distance elevation and grade analysis.', null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.filemodel', verbose_name='GPX Data'),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='highest_elevation',
            field=models.FloatField(blank=True, help_text='The highest altitude point measured along the recorded route. This metric helps determine alpine difficulty levels.', null=True, verbose_name='Highest Elevation'),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='lowest_elevation',
            field=models.FloatField(blank=True, help_text='The lowest altitude point measured along the route. This value defines the minimum elevation reached during the activity.', null=True, verbose_name='Lowest Elevation'),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='maximum_heart_rate',
            field=models.FloatField(blank=True, help_text='Highest measured heart rate recorded during the full activity. Highlights peak physical strain moments.', null=True, verbose_name='Maximum Heart Rate (bpm)'),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='maximum_speed',
            field=models.FloatField(blank=True, help_text='Highest travelling speed recorded during the activity. This value identifies the fastest moment captured.', null=True, verbose_name='Maximum Speed (km/h)'),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='minimum_heart_rate',
            field=models.FloatField(blank=True, help_text='Lowest measured heart rate captured during the activity. Useful for evaluating recovery stability.', null=True, verbose_name='Minimum Heart Rate (bpm)'),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='moving_ratio',
            field=models.FloatField(blank=True, help_text='Rate of time spent moving relative to the full activity. Indicates how constant the forward movement was.', null=True, verbose_name='Moving Ratio (%)'),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='moving_time',
            field=models.FloatField(blank=True, help_text='Total accumulated time during which the user was actively progressing along the route. All pauses and stationary intervals are excluded from this metric.', null=True, verbose_name='Moving Time (hours)'),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='pace_average',
            field=models.FloatField(blank=True, help_text='Average time needed to cover one kilometer. A lower value reflects stronger performance in forward progression.', null=True, verbose_name='Average Pace (min/km)'),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='pace_best',
            field=models.FloatField(blank=True, help_text='Fastest pace achieved during any continuous part of the activity. Marks the strongest recorded performance window.', null=True, verbose_name='Best Pace (min/km)'),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='start_time',
            field=models.DateTimeField(blank=True, help_text='Marks the exact time when the activity recording began. This value defines the starting point of the entire performance timeline.', null=True, verbose_name='Track Start Time'),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='steps_count',
            field=models.IntegerField(blank=True, help_text='Total number of steps taken during the full activity. This value is available only when step data exists.', null=True, verbose_name='Steps Count'),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='temperature_average',
            field=models.FloatField(blank=True, help_text='Average ambient temperature recorded throughout the activity. Helps assess environmental influence on effort.', null=True, verbose_name='Average Temperature (°C)'),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='total_time',
            field=models.FloatField(blank=True, help_text='Overall elapsed duration of the activity from start to end. Includes pauses, waiting periods and all non moving intervals.', null=True, verbose_name='Total Time (hours)'),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='track_types',
            field=models.JSONField(blank=True, help_text='Stores descriptive information about the route terrain. This may include surface type difficulty and structure segments.', null=True, verbose_name='Track Types'),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='weather_conditions',
            field=models.CharField(blank=True, help_text='General description of the surrounding weather observed during the activity. Examples include sunny stormy or foggy.', max_length=256, null=True, verbose_name='Weather Conditions'),
        ),
    ]
