# Generated by Django 5.2.5 on 2025-09-06 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorers', '0003_sectiontophotomodel_sectionmodel_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routemodel',
            name='best_months',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1, help_text='List of best months to complete this route.', verbose_name='Best Months'),
        ),
        migrations.AlterField(
            model_name='routemodel',
            name='best_seasons',
            field=models.IntegerField(choices=[(1, 'Winter'), (2, 'Spring'), (3, 'Summer'), (4, 'Autumn')], default=3, help_text='Best seasons for hiking this route.', verbose_name='Best Seasons'),
        ),
        migrations.AlterField(
            model_name='sectionmodel',
            name='best_months',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], default=1, help_text='List of best months to complete this route.', verbose_name='Best Months'),
        ),
        migrations.AlterField(
            model_name='sectionmodel',
            name='best_seasons',
            field=models.IntegerField(choices=[(1, 'Winter'), (2, 'Spring'), (3, 'Summer'), (4, 'Autumn')], default=3, help_text='Best seasons for hiking this route.', verbose_name='Best Seasons'),
        ),
    ]
