# Generated by Django 5.2.5 on 2025-09-13 14:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorers', '0003_remove_sectionmodel_sections_sectionmodel_cards_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionToRouteModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the object, automatically generated as a UUIDv4 value.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Stores the date and time when the object was firstly created. This timestamp field is automatically set when the object is created and cannot be modified after creation.', verbose_name='Created Timestamp')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Records the date and time when the object was last updated. This timestamp field is automatically updated whenever the object is modified.', verbose_name='Updated Timestamp')),
                ('position', models.IntegerField(default=10, help_text='Manual ordering within this relationship. Use gap indexing (10,20,30).', verbose_name='Position')),
                ('description', models.TextField(blank=True, help_text='A detailed description of the object. Supports plain text, rich text, or Markdown. Intended for contextual details such as terrain, difficulty level, notable landmarks, scenic highlights, and any other creator-provided insights.', null=True, verbose_name='Detail Description')),
                ('route', models.ForeignKey(help_text='The Route that is associated with the Section to Route M2M relationship.', on_delete=django.db.models.deletion.CASCADE, related_name='section_route_associations', to='explorers.routemodel', verbose_name='Route')),
                ('section', models.ForeignKey(help_text='The Section that is associated with the Section to Trip M2M relationship.', on_delete=django.db.models.deletion.CASCADE, related_name='section_trip_associations', to='explorers.sectionmodel', verbose_name='Section')),
            ],
            options={
                'verbose_name': 'Base Ordered Relationship Model',
                'verbose_name_plural': 'Base Ordered Relationship Models',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='routemodel',
            name='sections',
            field=models.ManyToManyField(help_text='Associated Sections.', related_name='section_routes', through='explorers.SectionToRouteModel', to='explorers.sectionmodel', verbose_name='Sections'),
        ),
        migrations.AddField(
            model_name='sectionmodel',
            name='routes',
            field=models.ManyToManyField(help_text='Sections that are part of this route.', related_name='route_sections', through='explorers.SectionToRouteModel', to='explorers.routemodel', verbose_name='Route Sections'),
        ),
    ]
