# Generated by Django 5.2.5 on 2025-09-13 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_rename_file_filemodel_path'),
        ('explorers', '0004_sectiontoroutemodel_routemodel_sections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionmodel',
            name='gpx_data',
            field=models.ForeignKey(blank=True, help_text='GPX data file.', null=True, on_delete=django.db.models.deletion.CASCADE, to='assets.filemodel', verbose_name='GPX Data'),
        ),
    ]
