# Generated by Django 5.2.5 on 2025-11-26 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorers', '0004_rename_duration_sectionmodel_estimated_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackmodel',
            name='journey',
            field=models.ForeignKey(help_text='Optional Journey that this Track belongs to. A Journey represents a multi-day, structured outdoor activity consisting of several individually recorded Tracks. This relationship allows grouping multiple daily segments or stages into a single overarching objective—such as a multi-day hike, trek, expedition, or thematic exploration route. Each Track contributes to the chronological and narrative structure of the Journey, capturing daily progress, environmental changes, and user performance over several days.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tracks', to='explorers.journeymodel', verbose_name='Related Journey'),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='route',
            field=models.ForeignKey(help_text='Optional reference to the official or user-defined Route that this Track most closely corresponds to. A Route represents a predefined path or trail in the AlpenWegs system, including its geometry, difficulty rating, elevation profile, and metadata. Assigning a Track to a Route establishes a conceptual link indicating that the user intended to follow, was inspired by, or largely adhered to a known trail. This relationship enables detailed analysis such as route-based similarity computation, automatic verification against official GPS geometry, and comparison of user performance across different attempts of the same Route.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tracks', to='explorers.routemodel', verbose_name='Related Route'),
        ),
    ]
