# Generated by Django 5.2.5 on 2025-12-15 09:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorers', '0006_alter_trackmodel_journey_alter_trackmodel_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackmodel',
            name='overall_average_speed',
        ),
        migrations.AddField(
            model_name='trackmodel',
            name='elevation',
            field=models.IntegerField(blank=True, help_text='Elevation in meters above sea level at the given GPX-derived location.', null=True, verbose_name='GPX Elevation (m a.s.l.)'),
        ),
        migrations.AddField(
            model_name='trackmodel',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Primary geographic reference point derived from the GPX track, stored as a PostGIS point in WGS84 coordinates.', null=True, srid=4326, verbose_name='GPX Location (WGS84)'),
        ),
    ]
