# Generated by Django 5.2.5 on 2025-12-16 13:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorers', '0007_remove_trackmodel_overall_average_speed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionmodel',
            name='elevation',
            field=models.IntegerField(blank=True, help_text='Elevation in meters above sea level at the given GPX-derived location.', null=True, verbose_name='GPX Elevation (m a.s.l.)'),
        ),
        migrations.AddField(
            model_name='sectionmodel',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Primary geographic reference point derived from the GPX track, stored as a PostGIS point in WGS84 coordinates.', null=True, srid=4326, verbose_name='GPX Location (WGS84)'),
        ),
        migrations.AlterField(
            model_name='trackmodel',
            name='windy_track',
            field=models.BooleanField(default=False, help_text='Indicates that the activity took place under strong or destabilizing wind conditions. Wind can influence balance, comfort, safety on exposed ridges, and perceived temperature.', verbose_name='Windy Conditions'),
        ),
    ]
