# Generated by Django 5.2.5 on 2025-09-03 21:18

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('compendiums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the object, automatically generated as a UUIDv4 value.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Stores the date and time when the object was firstly created. This timestamp field is automatically set when the object is created and cannot be modified after creation.', verbose_name='Created Timestamp')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Records the date and time when the object was last updated. This timestamp field is automatically updated whenever the object is modified.', verbose_name='Updated Timestamp')),
                ('name', models.CharField(help_text='The unique name that identifies this group.', max_length=150, unique=True, verbose_name='Group name')),
                ('permissions', models.ManyToManyField(blank=True, help_text='The permissions granted to this group. Users assigned to this group automatically inherit these.', to='auth.permission', verbose_name='Permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the object, automatically generated as a UUIDv4 value.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Stores the date and time when the object was firstly created. This timestamp field is automatically set when the object is created and cannot be modified after creation.', verbose_name='Created Timestamp')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Records the date and time when the object was last updated. This timestamp field is automatically updated whenever the object is modified.', verbose_name='Updated Timestamp')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates whether the user account is active.', verbose_name='Is Active')),
                ('is_staff', models.BooleanField(default=False, help_text='Indicates whether the user has staff privileges.', verbose_name='Is Staff')),
                ('email', models.EmailField(help_text="The user's unique email address, which serves as the primary authentication credential and unique identifier within the system. This email is required for logging in, password recovery, and receiving notifications or updates. Each email must be unique to ensure proper identification and prevent duplication of accounts.", max_length=128, unique=True, verbose_name='E-mail address')),
                ('username', models.CharField(help_text="A display name used to represent the user's in public views, comments, messages, and other interactions. This is not the user's official account name or login credential, but rather a presentation-friendly alias that helps protect the user's real name when preferred.", max_length=64, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(help_text="The user's given name, used for personalized communication. This field is required for proper user identification. It helps in addressing the user in messages, emails, and other interactions within the system.", max_length=64, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, help_text='An optional middle name field for users who have multiple given names. This can provide more precise identification but is not mandatory.', max_length=64, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(help_text="The user's surname name, used for personalized communication. This field is required for proper user identification. It helps in addressing the user in messages, emails, and other interactions within the system.", max_length=64, verbose_name='Last Name')),
                ('password_to_change', models.BooleanField(default=False, help_text='Indicates whether the user must change their password upon next login. This is typically set after an initial account setup or password reset to enhance security and ensure the user has set a personalized password.', verbose_name='Password change required')),
                ('phone_number', models.BigIntegerField(blank=True, help_text="User's phone number. It can be used for communication purposes such as account recovery or urgent notifications. This field is optional.", null=True, verbose_name='Phone number')),
                ('gender', models.IntegerField(blank=True, choices=[(0, 'Empty'), (1, 'Female'), (2, 'Male')], help_text="User's gender. This field can be used to personalize the user experience and address the user properly. It is optional.", null=True, verbose_name='Gender')),
                ('weight', models.FloatField(blank=True, help_text="User's weight in kilograms. This can be used to track health data or fitness goals. This field is optional.", null=True, verbose_name='Weight')),
                ('height', models.FloatField(blank=True, help_text="User's height in centimeters. This can be used to track health data or fitness goals. This field is optional.", null=True, verbose_name='Height')),
                ('bmi', models.FloatField(blank=True, help_text="User's Body Mass Index (BMI). It is calculated using the user's weight and height. This field is optional.", null=True, verbose_name='BMI')),
                ('birthday', models.DateTimeField(blank=True, help_text="User's birthdate. This can be used to calculate the user's age or personalize content.This field is optional.", null=True, verbose_name='Birthday')),
                ('location', models.CharField(blank=True, help_text="User's geographic location, which could be used for personalization or for tracking user activity. This field is optional.", max_length=128, null=True, verbose_name='Location')),
                ('location_name', models.CharField(blank=True, help_text="User's location name, such as city, town, or landmark. This field provides additional context to the user's geographical location and can help personalize their experience.", max_length=128, null=True, verbose_name='Location Name')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='user_set', related_query_name='user', to='profiles.groupmodel', verbose_name='Groups')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='UserToCardModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the object, automatically generated as a UUIDv4 value.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Stores the date and time when the object was firstly created. This timestamp field is automatically set when the object is created and cannot be modified after creation.', verbose_name='Created Timestamp')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Records the date and time when the object was last updated. This timestamp field is automatically updated whenever the object is modified.', verbose_name='Updated Timestamp')),
                ('card', models.ForeignKey(help_text='The card that the user owns or is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='user_card_associations', to='compendiums.cardmodel', verbose_name='Card')),
                ('user', models.ForeignKey(help_text='The user who owns or is associated with this card.', on_delete=django.db.models.deletion.CASCADE, related_name='card_user_associations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User to Card',
                'verbose_name_plural': 'Users to Cards',
            },
        ),
        migrations.AddConstraint(
            model_name='groupmodel',
            constraint=models.UniqueConstraint(fields=('name',), name='uniq_group_name'),
        ),
        migrations.AddConstraint(
            model_name='usermodel',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='uniq_user_email_lower'),
        ),
        migrations.AddConstraint(
            model_name='usermodel',
            constraint=models.CheckConstraint(condition=models.Q(('height__isnull', True), ('height__gt', 0), _connector='OR'), name='height_gt_zero_or_null'),
        ),
        migrations.AddConstraint(
            model_name='usermodel',
            constraint=models.CheckConstraint(condition=models.Q(('weight__isnull', True), ('weight__gt', 0), _connector='OR'), name='weight_gt_zero_or_null'),
        ),
    ]
