# Generated by Django 5.2.5 on 2025-08-10 10:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the object, automatically generated as a UUIDv4 value.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Stores the date and time when the object was firstly created. This timestamp field is automatically set when the object is created and cannot be modified after creation.', verbose_name='Created Timestamp')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Records the date and time when the object was last updated. This timestamp field is automatically updated whenever the object is modified.', verbose_name='Updated Timestamp')),
                ('email', models.EmailField(help_text="The user's unique email address, which serves as the primary authentication credential and unique identifier within the system. This email is required for logging in, password recovery, and receiving notifications or updates. Each email must be unique to ensure proper identification and prevent duplication of accounts.", max_length=255, unique=True, verbose_name='E-mail address')),
                ('password_to_change', models.BooleanField(default=False, help_text='Indicates whether the user must change their password upon next login. This is typically set after an initial account setup or password reset to enhance security and ensure the user has set a personalized password.', verbose_name='Password change required')),
                ('first_name', models.CharField(blank=True, help_text="The user's given name, used for personalized communication. This field is required for proper user identification. It helps in addressing the user in messages, emails, and other interactions within the system.", max_length=128, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, help_text='An optional middle name field for users who have multiple given names. This can provide more precise identification but is not mandatory.', max_length=128, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(blank=True, help_text="The user's surname name, used for personalized communication. This field is required for proper user identification. It helps in addressing the user in messages, emails, and other interactions within the system.", max_length=128, verbose_name='Last Name')),
                ('phone_number', models.BigIntegerField(blank=True, help_text="User's phone number. It can be used for communication purposes such as account recovery or urgent notifications. This field is optional.", null=True, verbose_name='Phone number')),
                ('gender', models.CharField(blank=True, help_text="User's gender. This field can be used to personalize the user experience and address the user properly. It is optional.", max_length=32, null=True, verbose_name='Gender')),
                ('weight', models.FloatField(blank=True, help_text="User's weight in kilograms. This can be used to track health data or fitness goals. This field is optional.", null=True, verbose_name='Weight')),
                ('height', models.FloatField(blank=True, help_text="User's height in centimeters. This can be used to track health data or fitness goals. This field is optional.", null=True, verbose_name='Height')),
                ('bmi', models.FloatField(blank=True, help_text="User's Body Mass Index (BMI). It is calculated using the user's weight and height. This field is optional.", null=True, verbose_name='BMI')),
                ('birthday', models.DateTimeField(blank=True, help_text="User's birthdate. This can be used to calculate the user's age or personalize content.This field is optional.", null=True, verbose_name='Birthday')),
                ('location', models.CharField(blank=True, help_text="User's geographic location, which could be used for personalization or for tracking user activity. This field is optional.", max_length=128, null=True, verbose_name='Location')),
                ('location_name', models.CharField(blank=True, help_text="User's location name, such as city, town, or landmark. This field provides additional context to the user's geographical location and can help personalize their experience.", max_length=128, null=True, verbose_name='Location Name')),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
            },
        ),
    ]
