# Generated by Django 5.2.5 on 2025-09-04 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupmodel',
            options={'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
    ]
