# Generated by Django 5.2.5 on 2025-09-01 21:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compendiums', '0002_remove_poimodel_details_description_and_more'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToCardModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='A unique identifier for the object, automatically generated as a UUIDv4 value.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Stores the date and time when the object was firstly created. This timestamp field is automatically set when the object is created and cannot be modified after creation.', verbose_name='Created Timestamp')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Records the date and time when the object was last updated. This timestamp field is automatically updated whenever the object is modified.', verbose_name='Updated Timestamp')),
                ('order', models.IntegerField(default=0, help_text='Defines the ordering or precedence of the relationship.', verbose_name='Order')),
                ('card', models.ForeignKey(help_text='The card that the user owns or is associated with.', on_delete=django.db.models.deletion.CASCADE, related_name='user_card_associations', to='compendiums.cardmodel', verbose_name='Card')),
                ('user', models.ForeignKey(help_text='The user who owns or is associated with this card.', on_delete=django.db.models.deletion.CASCADE, related_name='card_user_associations', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User to Card',
                'verbose_name_plural': 'Users to Cards',
            },
        ),
    ]
