# Generated by Django 5.2.5 on 2025-08-20 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usermodel',
            options={'default_permissions': (), 'permissions': (('read_write', 'Read and write access.'), ('read_only', 'Read only access')), 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
