# Generated by Django 5.2.5 on 2025-08-10 21:23

import django.db.models.functions.text
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membermodel',
            name='bmi',
        ),
        migrations.AddField(
            model_name='membermodel',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='membermodel',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='membermodel',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='membermodel',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membermodel',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Empty'), (1, 'Female'), (2, 'Male')], help_text="User's gender. This field can be used to personalize the user experience and address the user properly. It is optional.", null=True, verbose_name='Gender'),
        ),
        migrations.AddConstraint(
            model_name='membermodel',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), name='uniq_member_email_lower'),
        ),
        migrations.AddConstraint(
            model_name='membermodel',
            constraint=models.CheckConstraint(condition=models.Q(('height__isnull', True), ('height__gt', 0), _connector='OR'), name='height_gt_zero_or_null'),
        ),
        migrations.AddConstraint(
            model_name='membermodel',
            constraint=models.CheckConstraint(condition=models.Q(('weight__isnull', True), ('weight__gt', 0), _connector='OR'), name='weight_gt_zero_or_null'),
        ),
    ]
