# Generated by Django 5.2.5 on 2025-08-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_membermodel_bmi_membermodel_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='membermodel',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
