# Generated by Django 5.2.5 on 2025-08-12 19:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_membermodel_is_active_membermodel_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='membermodel',
            name='bmi',
            field=models.FloatField(blank=True, help_text="User's Body Mass Index (BMI). It is calculated using the member's weight and height. This field is optional.", null=True, verbose_name='BMI'),
        ),
        migrations.AddField(
            model_name='membermodel',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, help_text="A display name used to represent the member's in public views, comments, messages, and other interactions. This is not the member's official account name or login credential, but rather a presentation-friendly alias that helps protect the member's real name when preferred.", max_length=64, unique=True, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='birthday',
            field=models.DateTimeField(blank=True, help_text="User's birthdate. This can be used to calculate the member's age or personalize content.This field is optional.", null=True, verbose_name='Birthday'),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='email',
            field=models.EmailField(help_text="The member's unique email address, which serves as the primary authentication credential and unique identifier within the system. This email is required for logging in, password recovery, and receiving notifications or updates. Each email must be unique to ensure proper identification and prevent duplication of accounts.", max_length=128, unique=True, verbose_name='E-mail address'),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='first_name',
            field=models.CharField(help_text="The member's given name, used for personalized communication. This field is required for proper member identification. It helps in addressing the member in messages, emails, and other interactions within the system.", max_length=64, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Empty'), (1, 'Female'), (2, 'Male')], help_text="User's gender. This field can be used to personalize the member experience and address the member properly. It is optional.", null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indicates whether the member account is active.', verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Indicates whether the member has staff privileges.', verbose_name='Is Staff'),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='last_name',
            field=models.CharField(help_text="The member's surname name, used for personalized communication. This field is required for proper member identification. It helps in addressing the member in messages, emails, and other interactions within the system.", max_length=64, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='location',
            field=models.CharField(blank=True, help_text="User's geographic location, which could be used for personalization or for tracking member activity. This field is optional.", max_length=128, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='location_name',
            field=models.CharField(blank=True, help_text="User's location name, such as city, town, or landmark. This field provides additional context to the member's geographical location and can help personalize their experience.", max_length=128, null=True, verbose_name='Location Name'),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='middle_name',
            field=models.CharField(blank=True, help_text='An optional middle name field for members who have multiple given names. This can provide more precise identification but is not mandatory.', max_length=64, null=True, verbose_name='Middle Name'),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='password_to_change',
            field=models.BooleanField(default=False, help_text='Indicates whether the member must change their password upon next login. This is typically set after an initial account setup or password reset to enhance security and ensure the member has set a personalized password.', verbose_name='Password change required'),
        ),
    ]
