# Generated by Django 5.2.5 on 2025-08-12 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_membermodel_bmi_membermodel_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermodel',
            name='username',
            field=models.CharField(help_text="A display name used to represent the member's in public views, comments, messages, and other interactions. This is not the member's official account name or login credential, but rather a presentation-friendly alias that helps protect the member's real name when preferred.", max_length=64, unique=True, verbose_name='Username'),
        ),
    ]
