# Generated by Django 5.2.5 on 2025-08-28 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_usermodel_is_public'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='is_public',
        ),
    ]
