# Generated by Django 5.2.5 on 2025-09-03 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compendiums', '0001_initial'),
        ('explorers', '0001_initial'),
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmodel',
            name='creator',
            field=models.ForeignKey(help_text='Stores the unique identifier (UUID) of the user who created the object. This field is used to track ownership of the object.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='section',
            field=models.ManyToManyField(related_name='card_sections', through='explorers.SectionToCardModel', to='explorers.sectionmodel', verbose_name='Associated Sections'),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='users',
            field=models.ManyToManyField(help_text='Associated Users.', related_name='card_users', through='profiles.UserToCardModel', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
        migrations.AddField(
            model_name='poimodel',
            name='creator',
            field=models.ForeignKey(help_text='Stores the unique identifier (UUID) of the user who created the object. This field is used to track ownership of the object.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='poi',
            field=models.ForeignKey(help_text='Associated Point of Interest.', on_delete=django.db.models.deletion.PROTECT, to='compendiums.poimodel', verbose_name='Point of Interest'),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='creator',
            field=models.ForeignKey(help_text='Stores the unique identifier (UUID) of the user who created the object. This field is used to track ownership of the object.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='poimodel',
            name='region',
            field=models.ForeignKey(blank=True, help_text='The region to which this point of interest belongs. This establishes the geographical context for the PoI.', null=True, on_delete=django.db.models.deletion.CASCADE, to='compendiums.regionmodel', verbose_name='Region ID'),
        ),
    ]
