# Generated by Django 5.2.5 on 2025-09-01 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compendiums', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poimodel',
            name='details_description',
        ),
        migrations.RemoveField(
            model_name='regionmodel',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='regionmodel',
            name='longitude',
        ),
    ]
