# Generated by Django 5.2.5 on 2025-08-31 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compendiums', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmodel',
            name='creator',
            field=models.ForeignKey(help_text='Stores the unique identifier (UUID) of the user who created the object. This field is used to track ownership of the object.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='poimodel',
            name='creator',
            field=models.ForeignKey(help_text='Stores the unique identifier (UUID) of the user who created the object. This field is used to track ownership of the object.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='creator',
            field=models.ForeignKey(help_text='Stores the unique identifier (UUID) of the user who created the object. This field is used to track ownership of the object.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='poimodel',
            name='region',
            field=models.ForeignKey(blank=True, help_text='The region to which this point of interest belongs. This establishes the geographical context for the PoI.', null=True, on_delete=django.db.models.deletion.CASCADE, to='compendiums.regionmodel', verbose_name='Region ID'),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='region',
            field=models.ForeignKey(help_text='Associated Region.', on_delete=django.db.models.deletion.CASCADE, to='compendiums.regionmodel', verbose_name='Region'),
        ),
    ]
