# Generated by Django 5.2.5 on 2025-09-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compendiums', '0002_initial'),
        ('explorers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poimodel',
            name='sections',
            field=models.ManyToManyField(help_text='Associated Sections.', related_name='poi_sections', through='explorers.SectionToPoiModel', to='explorers.sectionmodel', verbose_name='Sections'),
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='sections',
            field=models.ManyToManyField(help_text='Associated Sections.', related_name='region_sections', through='explorers.SectionToRegionModel', to='explorers.sectionmodel', verbose_name='Sections'),
        ),
    ]
