# Generated by Django 5.2.5 on 2025-08-31 19:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compendiums', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardmodel',
            name='region',
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='poi',
            field=models.ForeignKey(default=django.utils.timezone.now, help_text='Associated Point of Interest.', on_delete=django.db.models.deletion.PROTECT, to='compendiums.poimodel', verbose_name='Point of Interest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='category',
            field=models.IntegerField(choices=[(101, 'Running'), (102, 'Hiking'), (104, 'Climbing'), (105, 'Via Ferrata'), (107, 'Trail Running'), (201, 'Winter Running'), (202, 'Winter Hiking'), (205, 'Snowshoeing'), (206, 'Ski Touring'), (207, 'Cross-Country Skiing'), (301, 'Biking'), (302, 'Mountain Biking'), (303, 'Downhill Biking')], default=102, help_text='The sport or activity associated with this card (e.g., hiking, via ferrata, climbing, biking).', verbose_name='Sport Category'),
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='category_specific_difficulty',
            field=models.CharField(blank=True, help_text='Difficulty level within the chosen sport category (e.g., T2 for hiking, K3 for via ferrata). Optional field.', max_length=32, null=True, verbose_name='Difficulty Level'),
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='description',
            field=models.TextField(help_text='Main text shown on the card (summary, story, or important information).', verbose_name='Card Description'),
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='elevation',
            field=models.FloatField(help_text='Approximate elevation (in meters above sea level) where the card’s feature is located.', verbose_name='Elevation (m a.s.l.)'),
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='type',
            field=models.CharField(choices=[(1, 'Mountain peak'), (2, 'Mountain range'), (3, 'Mountain hut'), (4, 'Mountain route'), (5, 'Mountain bridge'), (6, 'Mountain pass'), (7, 'Mountain trail'), (8, 'Mountain lake'), (9, 'Mountain cave'), (10, 'Mountain ruins'), (99, 'Special card')], default=1, help_text='Specifies the type of feature this card represents (e.g., mountain peak, hut, lake).', max_length=32, verbose_name='Card Type'),
        ),
    ]
