# Generated by Django 5.2.5 on 2025-12-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compendiums', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionmodel',
            name='type',
            field=models.IntegerField(choices=[(2, 'Canton'), (3, 'District'), (4, 'Municipality'), (10, 'Geographic region'), (11, 'Cultural region'), (12, 'Tourism region'), (20, 'Natural region'), (21, 'Mountain range'), (22, 'Valley'), (23, 'Plateau'), (24, 'Lake region'), (25, 'River basin'), (99, 'Special region')], default=2, help_text='Defines the logical type of the region, such as canton, geographic region, or natural region (e.g., Canton, Valley, Mountain Range).', verbose_name='Region Type'),
        ),
    ]
