# Generated by Django 5.2.5 on 2025-09-01 21:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compendiums', '0002_remove_poimodel_details_description_and_more'),
        ('explorers', '0001_initial'),
        ('profiles', '0002_usertocardmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cardmodel',
            name='section',
            field=models.ManyToManyField(related_name='card_sections', through='explorers.SectionToCardModel', to='explorers.sectionmodel', verbose_name='Associated Sections'),
        ),
        migrations.AddField(
            model_name='cardmodel',
            name='users',
            field=models.ManyToManyField(help_text='Associated Users.', related_name='card_users', through='profiles.UserToCardModel', to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
        migrations.AddField(
            model_name='poimodel',
            name='description',
            field=models.TextField(blank=True, help_text='Additional descriptive information about this PoI (historical notes, natural features, etc.).', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='description',
            field=models.TextField(blank=True, help_text='A detailed description of the object. Supports plain text, rich text, or Markdown. Intended for contextual details such as terrain, difficulty level, notable landmarks, scenic highlights, and any other creator-provided insights.', null=True, verbose_name='Object Description'),
        ),
        migrations.AlterField(
            model_name='poimodel',
            name='category',
            field=models.IntegerField(choices=[(1, 'City'), (2, 'Village'), (3, 'Mountain Hut'), (4, 'Mountain Peak'), (5, 'Lake'), (6, 'River'), (7, 'Mountain Pass'), (8, 'Forest Area'), (9, 'Glacier'), (10, 'Other')], default=10, help_text='Classification of this Point of Interest (e.g. City, Village, Hut, Peak, Lake, Pass).', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='poimodel',
            name='elevation',
            field=models.IntegerField(blank=True, help_text='Elevation of the PoI in meters above sea level.', null=True, verbose_name='Elevation (m a.s.l.)'),
        ),
        migrations.AlterField(
            model_name='poimodel',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude in decimal degrees (WGS84). Used for map display and spatial queries.', null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='poimodel',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude in decimal degrees (WGS84). Used for map display and spatial queries.', null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='poimodel',
            name='transport_description',
            field=models.BigIntegerField(blank=True, help_text='Information about how to reach this PoI (roads, trails, public transport).', null=True, verbose_name='Transport Description'),
        ),
    ]
