# Generated by Django 5.2.5 on 2025-09-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compendiums', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poimodel',
            name='description',
            field=models.TextField(blank=True, help_text='A detailed description of the object. Supports plain text, rich text, or Markdown. Intended for contextual details such as terrain, difficulty level, notable landmarks, scenic highlights, and any other creator-provided insights.', null=True, verbose_name='Object Description'),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='description',
            field=models.TextField(blank=True, help_text='A detailed description of the object. Supports plain text, rich text, or Markdown. Intended for contextual details such as terrain, difficulty level, notable landmarks, scenic highlights, and any other creator-provided insights.', null=True, verbose_name='Object Description'),
        ),
    ]
