# Generated by Django 5.2.5 on 2025-12-15 09:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compendiums', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poimodel',
            name='category',
            field=models.IntegerField(choices=[(1, 'Peak'), (2, 'Range'), (3, 'Hut'), (4, 'Route'), (5, 'Bridge'), (6, 'Pass'), (7, 'Trail'), (8, 'Lake'), (9, 'Cave'), (10, 'Ruins'), (11, 'Glacier'), (12, 'Cable Car Station'), (21, 'City'), (22, 'Village'), (23, 'Train Station'), (24, 'Parking Space'), (25, 'Restaurant'), (26, 'Bar'), (27, 'Accommodation'), (28, 'Tourist Information'), (41, 'Gemeinde'), (42, 'Canton'), (99, 'Other')], default=99, help_text='Classification of this Point of Interest (e.g. City, Village, Hut, Peak, Lake, Pass).', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='poimodel',
            name='elevation',
            field=models.IntegerField(blank=True, help_text='Elevation in meters above sea level at the given GPX-derived location.', null=True, verbose_name='GPX Elevation (m a.s.l.)'),
        ),
        migrations.AlterField(
            model_name='poimodel',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, help_text='Primary geographic reference point derived from the GPX track, stored as a PostGIS point in WGS84 coordinates.', null=True, srid=4326, verbose_name='GPX Location (WGS84)'),
        ),
    ]
