# Generated by Django 5.2.5 on 2025-09-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compendiums', '0003_alter_poimodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardmodel',
            name='description',
            field=models.TextField(blank=True, help_text='A detailed description of the object. Supports plain text, rich text, or Markdown. Intended for contextual details such as terrain, difficulty level, notable landmarks, scenic highlights, and any other creator-provided insights.', null=True, verbose_name='Detail Description'),
        ),
        migrations.AlterField(
            model_name='cardmodel',
            name='type',
            field=models.IntegerField(choices=[(1, 'Mountain peak'), (2, 'Mountain range'), (3, 'Mountain hut'), (4, 'Mountain route'), (5, 'Mountain bridge'), (6, 'Mountain pass'), (7, 'Mountain trail'), (8, 'Mountain lake'), (9, 'Mountain cave'), (10, 'Mountain ruins'), (99, 'Special card')], default=1, help_text='Specifies the type of feature this card represents (e.g., mountain peak, hut, lake).', verbose_name='Card Type'),
        ),
        migrations.AlterField(
            model_name='poimodel',
            name='description',
            field=models.TextField(blank=True, help_text='A detailed description of the object. Supports plain text, rich text, or Markdown. Intended for contextual details such as terrain, difficulty level, notable landmarks, scenic highlights, and any other creator-provided insights.', null=True, verbose_name='Detail Description'),
        ),
        migrations.AlterField(
            model_name='regionmodel',
            name='description',
            field=models.TextField(blank=True, help_text='A detailed description of the object. Supports plain text, rich text, or Markdown. Intended for contextual details such as terrain, difficulty level, notable landmarks, scenic highlights, and any other creator-provided insights.', null=True, verbose_name='Detail Description'),
        ),
    ]
